name: train_HAT_blind_SRx4
model_type: HATModel
scale: 4
num_gpu: auto
manual_seed: 0

# dataset and data loader settings
datasets:
  train:
    name: BlindDataset
    type: PairedImageDataset
    # 盲元训练集：GT 为不含盲元的清晰图，LQ 为含盲元的模糊图
    dataroot_gt: /home/student_server/Qtt/NAFNet/data/train_sharp
    dataroot_lq: /home/student_server/Qtt/NAFNet/data/train_blur
    io_backend:
      type: disk

    gt_size: 256
    use_hflip: true
    use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 6
    batch_size_per_gpu: 4
    # For small datasets, enlarge ratio helps provide more iterations
    # by repeating/reshuffling samples with augmentations.
    dataset_enlarge_ratio: 100
    prefetch_mode: ~

  val_1:
    name: BlindVal
    type: PairedImageDataset
    dataroot_gt: /home/student_server/Qtt/NAFNet/data/val_sharp
    dataroot_lq: /home/student_server/Qtt/NAFNet/data/val_blur
    io_backend:
      type: disk


# network structures (same as default HAT SRx4)
network_g:
  type: HAT
  upscale: 4
  in_chans: 3
  img_size: 64
  window_size: 16
  compress_ratio: 3
  squeeze_factor: 30
  conv_scale: 0.01
  overlap_ratio: 0.5
  img_range: 1.
  depths: [6, 6, 6, 6, 6, 6]
  embed_dim: 180
  num_heads: [6, 6, 6, 6, 6, 6]
  mlp_ratio: 2
  upsampler: 'pixelshuffle'
  resi_connection: '1conv'

# path
path:
  pretrain_network_g: ~
  param_key_g: 'params_ema'
  strict_load_g: false
  resume_state: ~

# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 1e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [125000, 200000, 225000, 240000]
    gamma: 0.5

  total_iter: 40800
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

# validation settings
val:
  # validate every ~5 epochs (102 it/epoch -> 102*5=510 it)
  val_freq: 510
  save_img: false
  pbar: False

  metrics:
    psnr:
      type: calculate_psnr
      crop_border: 4
      test_y_channel: true
      better: higher
    ssim:
      type: calculate_ssim
      crop_border: 4
      test_y_channel: true
      better: higher

# logging settings
logger:
  print_freq: 100
  # save checkpoint every ~5 epochs
  save_checkpoint_freq: 510
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
