name: train_HAT_blind_restoration
model_type: HATModel
scale: 1
num_gpu: 1
manual_seed: 0

datasets:
  train:
    name: BlindDataset
    type: PairedImageDataset
    dataroot_gt: /home/student_server/Qtt/NAFNet/data/train_sharp
    dataroot_lq: /home/student_server/Qtt/NAFNet/data/train_blur
    io_backend:
      type: disk
    gt_size: 96
    use_hflip: true
    use_rot: true
    use_shuffle: true
    num_worker_per_gpu: 4
    batch_size_per_gpu: 1
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val_1:
    name: BlindVal
    type: PairedImageDataset
    dataroot_gt: /home/student_server/Qtt/NAFNet/data/val_sharp
    dataroot_lq: /home/student_server/Qtt/NAFNet/data/val_blur
    io_backend:
      type: disk

network_g:
  type: HAT
  upscale: 1
  in_chans: 3
  img_size: 64
  window_size: 16
  compress_ratio: 3
  squeeze_factor: 30
  conv_scale: 0.01
  overlap_ratio: 0.5
  img_range: 1.
  depths: [6, 6, 6, 6, 6, 6]
  embed_dim: 180
  num_heads: [6, 6, 6, 6, 6, 6]
  mlp_ratio: 2
  upsampler: ''
  resi_connection: '1conv'
  use_checkpoint: true

path:
  pretrain_network_g: ~   # 或者删除该行
  param_key_g: 'params_ema'
  strict_load_g: false
  resume_state: ~

train:
  gradient_accumulation_steps: 1          # 若 batch_size=1 且单卡，可不累积
  use_amp: true
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: 0.0001
    weight_decay: 0.0001
    betas: [0.9, 0.999]
  scheduler:
    type: MultiStepLR
    milestones: [75000, 120000, 135000, 145000]   # 对应总迭代150k
    gamma: 0.5
  total_iter: 150000
  warmup_iter: 1500
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

val:
  val_freq: 2000
  save_img: false
  pbar: false
  metrics:
    psnr:
      type: calculate_psnr
      crop_border: 0          # 修复任务无需边界裁剪
      test_y_channel: true
      better: higher
    ssim:
      type: calculate_ssim
      crop_border: 0
      test_y_channel: true
      better: higher

logger:
  print_freq: 100
  save_checkpoint_freq: 0    # 只保留 best_model.pt
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~